services:
  api:
    build:
      context: backend
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_repo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: frontend
    ports:
      - 3000:3000
